# Generated by Django 5.2.7 on 2026-05-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_phone_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="state",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
