# Generated by Django 5.2.7 on 2026-05-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ai_insight_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="ai_limit_reset_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="elite_insight_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="premium_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
