[phases.setup]
nixPkgs = ["python3", "gcc", "pkg-config", "libmysqlclient-dev"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && MYSQLCLIENT_CFLAGS=$(mysql_config --cflags) MYSQLCLIENT_LDFLAGS=$(mysql_config --libs) pip install -r requirements.txt"]