# Generated by Django 5.2.7 on 2026-05-06 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kills", models.IntegerField(default=0)),
                ("deaths", models.IntegerField(default=0)),
                ("assists", models.IntegerField(default=0)),
                ("wins", models.IntegerField(default=0)),
                ("matches_played", models.IntegerField(default=0)),
                ("kd_ratio", models.FloatField(default=0.0)),
                ("win_rate", models.FloatField(default=0.0)),
                ("score", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="approved",
                        max_length=20,
                    ),
                ),
                (
                    "screenshot",
                    models.ImageField(blank=True, null=True, upload_to="screenshots/"),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player_game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="games.playergame",
                    ),
                ),
            ],
            options={
                "ordering": ["-score"],
            },
        ),
    ]
