# Generated by Django 5.2.7 on 2026-08-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerstats",
            name="draws",
            field=models.IntegerField(default=0),
        ),
    ]
