# Generated by Django 5.2.7 on 2026-08-14 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
        ("stats", "0002_playerstats_draws"),
    ]

    operations = [
        migrations.CreateModel(
            name="EfootballSquad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gk_type",
                    models.CharField(
                        choices=[
                            ("destroyer", "Destroyer"),
                            ("anchor_man", "Anchor Man"),
                            ("extra_frame", "Extra Frame"),
                            ("catalyst", "Catalyst"),
                            ("long_ball_expert", "Long Ball Expert"),
                            ("aerial_threat", "Aerial Threat"),
                            ("box_to_box", "Box-to-Box"),
                            ("deep_lying_playmaker", "Deep-Lying Playmaker"),
                            ("the_incisive_run", "The Incisive Run"),
                            ("prolific_winger", "Prolific Winger"),
                            ("cross_specialist", "Cross Specialist"),
                            ("speedster", "Speedster"),
                            ("goal_poacher", "Goal Poacher"),
                            ("target_man", "Target Man"),
                            ("dummy_runner", "Dummy Runner"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "cb1_type",
                    models.CharField(
                        choices=[
                            ("destroyer", "Destroyer"),
                            ("anchor_man", "Anchor Man"),
                            ("extra_frame", "Extra Frame"),
                            ("catalyst", "Catalyst"),
                            ("long_ball_expert", "Long Ball Expert"),
                            ("aerial_threat", "Aerial Threat"),
                            ("box_to_box", "Box-to-Box"),
                            ("deep_lying_playmaker", "Deep-Lying Playmaker"),
                            ("the_incisive_run", "The Incisive Run"),
                            ("prolific_winger", "Prolific Winger"),
                            ("cross_specialist", "Cross Specialist"),
                            ("speedster", "Speedster"),
                            ("goal_poacher", "Goal Poacher"),
                            ("target_man", "Target Man"),
                            ("dummy_runner", "Dummy Runner"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "cb2_type",
                    models.CharField(
                        choices=[
                            ("destroyer", "Destroyer"),
                            ("anchor_man", "Anchor Man"),
                            ("extra_frame", "Extra Frame"),
                            ("catalyst", "Catalyst"),
                            ("long_ball_expert", "Long Ball Expert"),
                            ("aerial_threat", "Aerial Threat"),
                            ("box_to_box", "Box-to-Box"),
                            ("deep_lying_playmaker", "Deep-Lying Playmaker"),
                            ("the_incisive_run", "The Incisive Run"),
                            ("prolific_winger", "Prolific Winger"),
                            ("cross_specialist", "Cross Specialist"),
                            ("speedster", "Speedster"),
                            ("goal_poacher", "Goal Poacher"),
                            ("target_man", "Target Man"),
                            ("dummy_runner", "Dummy Runner"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "cdm_type",
                    models.CharField(
                        choices=[
                            ("destroyer", "Destroyer"),
                            ("anchor_man", "Anchor Man"),
                            ("extra_frame", "Extra Frame"),
                            ("catalyst", "Catalyst"),
                            ("long_ball_expert", "Long Ball Expert"),
                            ("aerial_threat", "Aerial Threat"),
                            ("box_to_box", "Box-to-Box"),
                            ("deep_lying_playmaker", "Deep-Lying Playmaker"),
                            ("the_incisive_run", "The Incisive Run"),
                            ("prolific_winger", "Prolific Winger"),
                            ("cross_specialist", "Cross Specialist"),
                            ("speedster", "Speedster"),
                            ("goal_poacher", "Goal Poacher"),
                            ("target_man", "Target Man"),
                            ("dummy_runner", "Dummy Runner"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "lw_type",
                    models.CharField(
                        choices=[
                            ("destroyer", "Destroyer"),
                            ("anchor_man", "Anchor Man"),
                            ("extra_frame", "Extra Frame"),
                            ("catalyst", "Catalyst"),
                            ("long_ball_expert", "Long Ball Expert"),
                            ("aerial_threat", "Aerial Threat"),
                            ("box_to_box", "Box-to-Box"),
                            ("deep_lying_playmaker", "Deep-Lying Playmaker"),
                            ("the_incisive_run", "The Incisive Run"),
                            ("prolific_winger", "Prolific Winger"),
                            ("cross_specialist", "Cross Specialist"),
                            ("speedster", "Speedster"),
                            ("goal_poacher", "Goal Poacher"),
                            ("target_man", "Target Man"),
                            ("dummy_runner", "Dummy Runner"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "rw_type",
                    models.CharField(
                        choices=[
                            ("destroyer", "Destroyer"),
                            ("anchor_man", "Anchor Man"),
                            ("extra_frame", "Extra Frame"),
                            ("catalyst", "Catalyst"),
                            ("long_ball_expert", "Long Ball Expert"),
                            ("aerial_threat", "Aerial Threat"),
                            ("box_to_box", "Box-to-Box"),
                            ("deep_lying_playmaker", "Deep-Lying Playmaker"),
                            ("the_incisive_run", "The Incisive Run"),
                            ("prolific_winger", "Prolific Winger"),
                            ("cross_specialist", "Cross Specialist"),
                            ("speedster", "Speedster"),
                            ("goal_poacher", "Goal Poacher"),
                            ("target_man", "Target Man"),
                            ("dummy_runner", "Dummy Runner"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "st_type",
                    models.CharField(
                        choices=[
                            ("destroyer", "Destroyer"),
                            ("anchor_man", "Anchor Man"),
                            ("extra_frame", "Extra Frame"),
                            ("catalyst", "Catalyst"),
                            ("long_ball_expert", "Long Ball Expert"),
                            ("aerial_threat", "Aerial Threat"),
                            ("box_to_box", "Box-to-Box"),
                            ("deep_lying_playmaker", "Deep-Lying Playmaker"),
                            ("the_incisive_run", "The Incisive Run"),
                            ("prolific_winger", "Prolific Winger"),
                            ("cross_specialist", "Cross Specialist"),
                            ("speedster", "Speedster"),
                            ("goal_poacher", "Goal Poacher"),
                            ("target_man", "Target Man"),
                            ("dummy_runner", "Dummy Runner"),
                        ],
                        max_length=30,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player_game",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="efootball_squad",
                        to="games.playergame",
                    ),
                ),
            ],
        ),
    ]
